name: Update Publications

on:
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch:

jobs:
  update-publications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update README publications
        env:
          ORCID_ID: ${{ secrets.ORCID_ID || '0009-0002-0202-7891' }}
          AUTHOR_NAME: ${{ secrets.AUTHOR_NAME || 'Pappuraj Bhottacharjee' }}
          MAX_PUBLICATIONS: 12
        run: |
          python .github/scripts/update_publications.py

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update publications section"
            git push
          else
            echo "No changes to commit."
          fi
